package com.pipeline.infrastructure;

import com.pipeline.domain.Stage;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Enumerated;
import jakarta.persistence.EnumType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Version;
import java.time.Instant;
import java.util.UUID;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

/**
 * is_terminal is mapped read-only. It was unmapped until file 08, on the grounds that the
 * database generates it and mapping it would invite Hibernate to try to write it; the
 * second half of that is handled by insertable=false, updatable=false, and the first half
 * turned out to be a reason to map it rather than not.
 *
 * <p>Search needs to be able to say "AND NOT is_terminal" in a query, and that conjunct is
 * not optional: V5's partial index is only reachable through it, and re-measuring at 50k
 * rows confirms the planner falls back to a broader index and a filter without it. The
 * column is the only spelling its predicate prover will match.
 */
@Entity
@Table(name = "candidate")
class CandidateEntity {

    @Id
    UUID id;

    UUID jobId;
    String fullName;

    // columnDefinition is what makes ddl-auto=validate accept these: Hibernate
    // otherwise expects varchar for a String and derives "eventtype" for the enum
    // below, neither of which is what file 02 created.
    @Column(columnDefinition = "citext")
    String email;
    String phone;
    String source;

    @Enumerated(EnumType.STRING)
    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    @Column(columnDefinition = "stage")
    Stage currentStage;

    Instant currentStageSince;
    short reachedMask;

    /** Generated by the database; readable so search can filter on it, never written. */
    @Column(insertable = false, updatable = false)
    boolean isTerminal;

    Instant createdAt;

    @Version
    int version;

    protected CandidateEntity() {}

    CandidateEntity(
            UUID id,
            UUID jobId,
            String fullName,
            String email,
            String phone,
            String source,
            Stage currentStage,
            Instant currentStageSince,
            short reachedMask,
            Instant createdAt) {
        this.id = id;
        this.jobId = jobId;
        this.fullName = fullName;
        this.email = email;
        this.phone = phone;
        this.source = source;
        this.currentStage = currentStage;
        this.currentStageSince = currentStageSince;
        this.reachedMask = reachedMask;
        this.createdAt = createdAt;
    }
}
